### ISSUE TITLE
Selecting a value in DropdownField makes the field jump upward

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-admin#660]
**Version: 4.3.x-dev**

With tractorcow/silverstripe-fluent 4.2.x-dev

* Go to locales
* Add a new locale
* Choose a value from the Locale dropdown
* Notice the field jumps upwards

![image](https://user-images.githubusercontent.com/5170590/46009671-93292080-c0c0-11e8-803f-c1344d0d086b.png)

![image](https://user-images.githubusercontent.com/5170590/46009663-8c021280-c0c0-11e8-8fb8-487a48298146.png)

**Comment by ScopeyNZ** [comment]
Note this only appears to happen for Chrome. The latest version of Firefox is fine for me.

**Comment by robbieaverill** [comment]
PR at #681

**Comment by maxime-rainville** [comment]
Solved by #681.

**Comment by robbieaverill** [comment]
I can still reproduce this in some cases, for example in Security:

* Create a new member
* Tab through the fields
* Once you pass the Interface Language dropdown, notice the behaviour

**Comment by robbieaverill** [comment]
Still occurring in 4.3.2

**Comment by maxime-rainville** [comment]
Not seeing it on 4.x with Firefox.

**Comment by robbieaverill** [comment]
I should've been more specific, sorry. It's occurring for me in 4.3.2 on Chrome 72/MacOS Mojave

**Comment by mithungc** [comment]
Issue still occurs in 4.3.
To reproduce the issue, you need to Keyboard 'Tab in' to the field and then 'Tab Out' of it.

**Comment by maxime-rainville** [comment]
I see it now in Chrome.

**Comment by robbieaverill** [comment]
Also present in 4.4.0-rc1
